### ISSUE TITLE
RuntimeException at launch on v3.2.3, unable to initialize an effect engine

### ISSUE THREAD

**Issue by brarcher** [SimpleMobileTools/Simple-Music-Player#122]
First, thanks for the great apps which you are creating!

I'm finding that v3.2.3 from F-Droid is unable to launch on Android 7.1 (LineageOS) on a Galaxy S4 due to a failure to initialize an effect engine. Before that it is also hitting a ClassNotFoundException, though it may be unrelated.

```
03-15 23:38:19.323   595 18772 I ActivityManager: Start proc 16963:com.simplemobiletools.musicplayer/u0a124 for activity com.simplemobiletools.musicplayer/.activities.SplashActivity
03-15 23:38:19.408 16963 16963 W System  : ClassLoader referenced unknown path: /mnt/expand/77ce1534-5a43-426c-af16-32c490dc01b9/app/com.simplemobiletools.musicplayer-1/lib/arm
03-15 23:38:19.499   595  1542 I ActivityManager: START u0 {cmp=com.simplemobiletools.musicplayer/.activities.MainActivity} from uid 10124 on display 0
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.Class.classForName(Native Method)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:400)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:326)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.support.v7.app.j.b(SourceFile:1014)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.support.v7.app.j.onCreateView(SourceFile:1092)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1821)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2555)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2628)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:158)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.Activity.performCreateCommon(Activity.java:6679)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.Activity.performCreate(Activity.java:6686)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.os.Looper.loop(Looper.java:154)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/mnt/expand/77ce1534-5a43-426c-af16-32c490dc01b9/app/com.simplemobiletools.musicplayer-1/base.apk"],nativeLibraryDirectories=[/mnt/expand/77ce1534-5a43-426c-af16-32c490dc01b9/app/com.simplemobiletools.musicplayer-1/lib/arm, /system/lib, /vendor/lib]]
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-15 23:38:19.526 16963 16963 I AppCompatDelegate: 	... 28 more
```
```
03-15 23:38:20.103 16963 16963 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
03-15 23:38:20.103 16963 16963 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
03-15 23:38:20.131   259   259 W APM::EffectDescriptor: registerEffect() memory limit exceeded for Fx Equalizer, Memory 25 KB
03-15 23:38:20.131 16963 16963 E AudioEffect: set(): AudioFlinger could not create effect, status: -38
03-15 23:38:20.131 16963 16963 E AudioEffects-JNI: AudioEffect initCheck failed -3
03-15 23:38:20.131 16963 16963 E AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
03-15 23:38:20.132 16963 16963 D AndroidRuntime: Shutting down VM
03-15 23:38:20.134 16963 16963 E AndroidRuntime: FATAL EXCEPTION: main
03-15 23:38:20.134 16963 16963 E AndroidRuntime: Process: com.simplemobiletools.musicplayer, PID: 16963
03-15 23:38:20.134 16963 16963 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.simplemobiletools.musicplayer.services.MusicService: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3226)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.simplemobiletools.musicplayer.services.MusicService.A(SourceFile:290)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.simplemobiletools.musicplayer.services.MusicService.x(SourceFile:248)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.simplemobiletools.musicplayer.services.MusicService.t(SourceFile:113)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at com.simplemobiletools.musicplayer.services.MusicService.onCreate(SourceFile:86)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3216)
03-15 23:38:20.134 16963 16963 E AndroidRuntime: 	... 8 more
03-15 23:38:20.139   595  1568 W ActivityManager:   Force finishing activity com.simplemobiletools.musicplayer/.activities.MainActivity
```

**Comment by tibbi** [comment]
this is an old issue, reopen if it is still broken in 5.2.2
